import "@repo/ui/styles.css";
import type { Metadata } from "next";
// 디자인 시스템 스타일보다 뒤에 위치해야 합니다.
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
