import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// 디자인 시스템 스타일보다 뒤에 위치해야 합니다.
import QueryProvider from "@/components/query-provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
