version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    command: redis-server --requirepass 9999 --port 6379
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - '8001:8001'
    networks:
      - redis-network
    volumes:
      - redis-insight-data:/db

volumes:
  redis-data:
  redis-insight-data:

networks:
  redis-network:
    driver: bridge
